### ISSUE TITLE
请问什么时候可以下载到论文啊，很感兴趣。

### ISSUE THREAD

**Issue by wangzc1997** [liuzh-buaa/nfbst#1]
我看到公众号说已经在 AAAI24 上发表了，但是一直搜不到论文可以下载，想看看内容。谢谢

**Comment by liuzh-buaa** [comment]
邮件已经收到，祝好！liuzh

**Comment by liuzh-buaa** [comment]
感谢关注！目前论文已被accept，正在修改camera-ready版本，之后我们会及时更新到GitHub上

**Comment by liuzh-buaa** [comment]
Thank you for your attention. We have updated our paper in arXiv.
https://arxiv.org/abs/2401.13335
